CREATE TABLE IF NOT EXISTS diaries (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,

  title VARCHAR(200) NOT NULL,
  diary_date DATE NOT NULL,
  content TEXT NOT NULL,

  original_file_name VARCHAR(255) NULL,
  stored_file_name VARCHAR(500) NULL,
  file_size BIGINT NULL,

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
